### ISSUE TITLE
[dist-git-to-src-git] TODO

### ISSUE THREAD

**Issue by jpopelka** [packit-service/research#33]
Just tried `dist-git-to-src-git` and it worked like a charm.
There are however few things that need to be changed/added for `packit` to be able to use the created source-git repo.

I was expecting to see individual commits for each downstream patch, however, I found only one commit - maybe I'm looking at wrong place.

So before we start applying downstream patches we need to:
```bash
$ echo "upstream_ref: c8s-sg-start" > .packit.yaml
$ git add .packit.yaml; git commit -am ".packit.yaml"
$ git tag c8s-sg-start HEAD
for patch in downstream-patches:
  if is git patch:
    git am patch
  else:
    patch -p1 --verbose --fuzz=0 <patch
    git commit -am "fix"
```

I'll update this description tomorrow, this is how I see it now.

**Comment by csomh** [comment]
dist2src does a dist-git commit to source-git commit mapping currently, because it has no knowledge of the upstream history (only the dist-git history). So tracking future dist-git history, that is: updating the source-git history when there is a new commit in dist-git, would be problematic. What do we do with the individual commits applying the downstream patches, for example? How do we deal with them but still have a linear source-git history, instead of just rewriting all?

The ideal long term solution might be to make dist2src aware of the upstream history (i.e. the commit ref corresponding to the archive found in the lookaside cache), and apply the patches on top of that.

We can discuss more in person.

**Comment by TomasTomecek** [comment]
what's the status here?

**Comment by jpopelka** [comment]
Should be done with https://github.com/packit-service/dist-git-to-source-git/pull/2

Closing
